name: booking_restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.0
  dartz: ^0.10.1
  dependency_injection_flutter: ^2.0.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_polyline_points: ^3.0.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^8.2.0
  google_maps_flutter: ^2.12.3
  google_sign_in: ^7.1.1
  image_picker: ^1.1.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/svgs/