// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFsBgDf4V4Kcs2i9zyWnYas9utSC3kc40',
    appId: '1:125337987586:web:eff275dda1a112db1e551b',
    messagingSenderId: '125337987586',
    projectId: 'booking-restaurant-app-63945',
    authDomain: 'booking-restaurant-app-63945.firebaseapp.com',
    storageBucket: 'booking-restaurant-app-63945.firebasestorage.app',
    measurementId: 'G-T0MEYDWK4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkjlP2KSI2p1f8sSdHASTocnl9qQx8Prk',
    appId: '1:125337987586:android:160c8e7444749e351e551b',
    messagingSenderId: '125337987586',
    projectId: 'booking-restaurant-app-63945',
    storageBucket: 'booking-restaurant-app-63945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlMsvjZKjqSyOdnls4xkiq_-F9p_Pxvro',
    appId: '1:125337987586:ios:92b870a8e02404af1e551b',
    messagingSenderId: '125337987586',
    projectId: 'booking-restaurant-app-63945',
    storageBucket: 'booking-restaurant-app-63945.firebasestorage.app',
    iosBundleId: 'com.example.bookingRestaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlMsvjZKjqSyOdnls4xkiq_-F9p_Pxvro',
    appId: '1:125337987586:ios:92b870a8e02404af1e551b',
    messagingSenderId: '125337987586',
    projectId: 'booking-restaurant-app-63945',
    storageBucket: 'booking-restaurant-app-63945.firebasestorage.app',
    iosBundleId: 'com.example.bookingRestaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFsBgDf4V4Kcs2i9zyWnYas9utSC3kc40',
    appId: '1:125337987586:web:9bdc2c083cb6f9861e551b',
    messagingSenderId: '125337987586',
    projectId: 'booking-restaurant-app-63945',
    authDomain: 'booking-restaurant-app-63945.firebaseapp.com',
    storageBucket: 'booking-restaurant-app-63945.firebasestorage.app',
    measurementId: 'G-RCLJDX57JF',
  );
}
